[project]
name = "igex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ibrah1m208", email = "md.ibrahim.bin.faisal@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
igex = "igex:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
